#
# bento-box
# continous integration (ci) pipeline
#

name: "CI Pipeline"
on: push
env:
  DOCKER_BUILDKIT: 1
jobs:
  # build & push docker images
  build-push-imgs:
    runs-on: ubuntu-20.04
    name: "Build & Push Docker Images"
    steps:
      - uses: actions/checkout@v2
      - name: "Build Docker Images"
        run: |
          make build
      - name: "Authenticate with Container Registry"
        env:
          DOCKER_TOKEN: ${{secrets.GHCR_TOKEN}}
        run: |
          echo $DOCKER_TOKEN | docker login ghcr.io --username mrzzy --password-stdin
      - name: "Push Docker Images"
        run: |
          make push
